sudo: required
services:
  - docker

before_install:
  - docker build -t ssundararaj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssundararaj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-663076771503"
  bucket_path: "docker-react"
  on:
    branch: master